### ISSUE TITLE
Total Size of Removed Items (Feature Request)

### ISSUE THREAD

**Issue by buginanet** [enriquesomolinos/pkgRipper#10]
This is an excellent program! Would it be possible to add a feature to sum up the size of all the items to be removed and easily see how much smaller the file will be?

Sometimes, the update files don't have too many files in common with the base, sometimes there are a lot. Currently you can only look at the list of all the files and their sizes to decide if you want to make the patch and rip the base pkg. If while making the patch we could quickly and easily see something like, "Ripped pkg will 5gb smaller" or something like that, I think it would be a really helpful feature!

**Comment by enriquesomolinos** [comment]
Done in v2.5.0
