### ISSUE TITLE
Heres a manual for beginners

### ISSUE THREAD

**Issue by PhR34x0r** [enriquesomolinos/pkgRipper#15]
Hi there,
since your great tool helped me save a lot of space, i wrote a quick manual to get more ppl started.
If its not wanted/good enough, just delete.
The pdf has the original file embeded and can be directly edited in LibreOffice.

BR
[](url
[PKGRipper Manual.pdf](https://github.com/enriquesomolinos/pkgRipper/files/8004824/PKGRipper.Manual.pdf)
)

**Comment by chronoss09** [comment]
Super cool ;)

**Comment by enriquesomolinos** [comment]
wow! thanks for sharing, i'll put in the main page :)
