### ISSUE TITLE
get this error 

### ISSUE THREAD

**Issue by Fall0n** [enriquesomolinos/pkgRipper#2]
Hope that you can help me.. i get this error try make only eng in cyberpunk 2077

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards, Collection`1 Results)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards)
   at PkgRipper.Form1.OpenFileDialog1_FileOk(Object sender, CancelEventArgs e)
   at System.Windows.Forms.FileDialog.OnFileOk(CancelEventArgs e)
   at System.Windows.Forms.FileDialog.HandleVistaFileOk(IFileDialog dialog)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PkgRipper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Temp/Ps4/PS4-Fake-PKG-Tools-3.87-main/PkgRipper.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9014.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by enriquesomolinos** [comment]
maybe the folder you put pkgripper is too long, try in a sort path with no special chars

**Comment by enriquesomolinos** [comment]
@Fall0n can you do a merge request with the patch file you want to use?

**Comment by Fall0n** [comment]
> @Fall0n can you do a merge request with the patch file you want to use?

How do i make make a merge request? Its the game and update 1.31 i hope have only eng..

**Comment by RiPPERD** [comment]
Fall0n are you using 32bit windows? maybe it needs 64bit.

also patches are easy to make, just edit the patch file included with the correct info....

so file paths, game titles etc... good app but does require work to make patches but then its simple after that

**Comment by Fall0n** [comment]
> Fall0n are you using 32bit windows? maybe it needs 64bit.
> 
> 
> 
> also patches are easy to make, just edit the patch file included with the correct info....
> 
> 
> 
> so file paths, game titles etc... good app but does require work to make patches but then its simple after that

In on x64 bit win10 PRO

Have try just get the error i have post. Hope there is a way fix this

**Comment by enriquesomolinos** [comment]
> > Fall0n are you using 32bit windows? maybe it needs 64bit.
> > also patches are easy to make, just edit the patch file included with the correct info....
> > so file paths, game titles etc... good app but does require work to make patches but then its simple after that
> 
> In on x64 bit win10 PRO
> 
> Have try just get the error i have post. Hope there is a way fix this

can you share the patch file you are using? Also can you move the pgkripper app and contents to a root folder like c:\pkgripper?

**Comment by Fall0n** [comment]
Can you make update that make it work? Like patch fix pkgripper?

**Comment by enriquesomolinos** [comment]
for you cyberpunk backup you need a custom patch file, at this moment pkgripper only provides patches for f12020 nascar ignition and transformers battleground, in order to remove content of cyberpunk you must create a custom patch file

**Comment by RiPPERD** [comment]
use genps4.exe to print out a file list for the game your trying, let me know what language you want left in there.

i will then send you the patch file so you can see how it works

**Comment by enriquesomolinos** [comment]
In a few days we will have a patch creator gui to create our custom patches easy. It will use orbis-pub-cmd to retrieve image contents, will have the functionality to detect duplicated files from updates and more

**Comment by Fall0n** [comment]
> In a few days we will have a patch creator gui to create our custom patches easy. It will use orbis-pub-cmd to retrieve image contents, will have the functionality to detect duplicated files from updates and more

I hold off to the patch creator gui is out. Hope it make it easy for me

**Comment by enriquesomolinos** [comment]
@Fall0n  try to use the patch creator

**Comment by Fall0n** [comment]
Where can i find the patch creator you talking aboute?

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Enrique Somolinos Pérez ***@***.***>
Skickat: Wednesday, January 5, 2022 5:07:59 PM
Till: enriquesomolinos/pkgRipper ***@***.***>
Kopia: Fall0n ***@***.***>; Mention ***@***.***>
Ämne: Re: [enriquesomolinos/pkgRipper] get this error (Issue #2)


Closed #2<https://github.com/enriquesomolinos/pkgRipper/issues/2>.

**Comment by enriquesomolinos** [comment]
Donwload the latest release

**Comment by Fall0n** [comment]
It give me same error

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Enrique Somolinos Pérez ***@***.***>
Skickat: Wednesday, January 5, 2022 5:57:26 PM
Till: enriquesomolinos/pkgRipper ***@***.***>
Kopia: Fall0n ***@***.***>; Mention ***@***.***>
Ämne: Re: [enriquesomolinos/pkgRipper] get this error (Issue #2)


Donwload the latest release

**Comment by enriquesomolinos** [comment]
please add a screenshot

**Comment by Fall0n** [comment]
Just to check i have formate my harddrive and reinstall win 10 check if my win 10 brokend

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Enrique Somolinos Pérez ***@***.***>
Skickat: Wednesday, January 5, 2022 6:04:42 PM
Till: enriquesomolinos/pkgRipper ***@***.***>
Kopia: Fall0n ***@***.***>; Mention ***@***.***>
Ämne: Re: [enriquesomolinos/pkgRipper] get this error (Issue #2)


please add a screenshot
