### ISSUE TITLE
Wrong patches

### ISSUE THREAD

**Issue by RiPPERD** [enriquesomolinos/pkgRipper#3]
Hello, 

you may know my name from the ps4 scene, since i was referenced in the post on psxhax i thought id try this tool out.

I opened up a game called knowledge is power, it then detects the game fine, however the only patch file i have is the F1 2020 game that you included.... but the app tells me this:
Game detected
Patch files detected correctly

the patch file cannot be correct as the game doesnt match.

love the idea though mate, myself and another guy used to make RipKits for PSP and PS3 back in those days, i would be happy to help you adapt this and make it a bit more user friendly... let me know.

i have 0 .net knowledge so all coding would be done by you but i do know the orbis commands etc and also how to make the patch files that are needed for your app as i had a look at the patch file... pretty simple but obviously you need more users to create the patches... this is why my app didnt take off so well as the end users didnt know how to use it lol

I have tried loggin into psxhax but seems my account is blocked... lets me login then nothing is displayed on the pages, if someone can contact admin on psxhax that would be great.

Regards
RiPPERD

**Comment by enriquesomolinos** [comment]
hi @RiPPERD , this week i'll try to fix this error and I want to create a system to make patches in an easier way

**Comment by RiPPERD** [comment]
> hi @RiPPERD , this week i'll try to fix this error and I want to create a system to make patches in an easier way

unfortunately because of the way each game is different making the patch files wont be that simple... however if you implemented PKG VIEW option then users could select the files they wanted to remove (maybe by double click or similar, would need to work in multiple folders) then your app could save a patch file from user selection... then apply patch via normal method

**Comment by enriquesomolinos** [comment]
> > hi @RiPPERD , this week i'll try to fix this error and I want to create a system to make patches in an easier way
> 
> unfortunately because of the way each game is different making the patch files wont be that simple... however if you implemented PKG VIEW option then users could select the files they wanted to remove (maybe by double click or similar, would need to work in multiple folders) then your app could save a patch file from user selection... then apply patch via normal method

Yes you rigth, I have some ideas like that and in the next days I try to implement it. I think if there is no need to know xml or anything technical it can allow pkgripper to grow fastly.

**Comment by RiPPERD** [comment]
ok well if you want any help let me know, i want to get back into the ps4 scene again now further firmwares are broken... got bored with only 5.05 stuff and lost heart in it... making mods etc is my passion really.
