### ISSUE TITLE
MediEvil HD 

### ISSUE THREAD

**Issue by Androxilogin** [enriquesomolinos/pkgRipper#4]
I ripped my copy and CUSA11227 is the number I get. The program says the patch is unavailable. Closer examination, the patch says CUSA12982. I attempted simply renaming the patch to match my number as well as the internals to no avail.

**Comment by enriquesomolinos** [comment]
Hi @Androxilogin , you need to do:

- Obtain the content_id. Simply you can copy it from pkgripper when you open the pkg. Its value is like EP9000-CUSA12982_00-MEDIEVILHD000001
- Copy the EP9000-CUSA12982_00-MEDIEVILHD000001.xml with the content_id obtained in the previus step
- In the xml file modify the title_id="CUSA12982" content_id="EP9000-CUSA12982_00-MEDIEVILHD000001" with the correct values.
- Check the files of the patch and the update version you know if all can work fine.
- Finally, I apreciate you to share this new file with community via https://github.com/enriquesomolinos/pkgripper-patches

**Comment by Androxilogin** [comment]
I found my problem. At the beginning of the file, I wasn't replacing **EP**9000-CUSA11227_00-MEDIEVILHD000001 with the new value, which should have been **UP**9000-CUSA11227_00-MEDIEVILHD000001.

I would add this to your patches, however, I am faced with this message:

Uploads are disabled.
File uploads require push access to this repository.

So I will attach it below.

[UP9000-CUSA11227_00-MEDIEVILHD000001.zip](https://github.com/enriquesomolinos/pkgRipper/files/7878564/UP9000-CUSA11227_00-MEDIEVILHD000001.zip)
