### ISSUE TITLE
HOW TO USE THE PROGRAM IF I HAVE BOTH BASE AND UPDATE?

### ISSUE THREAD

**Issue by chicco83** [enriquesomolinos/pkgRipper#5]
hi,
if i have both the base pkg and the update pkg have. how have i to procedd?
have i to apply the patch to the base file or to the update pgk? or to both?

thanks

**Comment by enriquesomolinos** [comment]
Normally you need to patch the base pkg and then the update to remarry with the base.

**Comment by chicco83** [comment]
so i patch the original base and i obtain a new base.
then i patch the update and i have to select the base to remarry.
at this point have i to use the new base created in the first step?

**Comment by enriquesomolinos** [comment]
you are right, you need to remarry with the new base pkg
