### ISSUE TITLE
FAR CRY 6 (CUSA15778) error 

### ISSUE THREAD

**Issue by wardo123-2** [enriquesomolinos/pkgRipper#7]
the error i have is that the program cannot find the patches for the game, the patch is already in the program folder ("patches"), the title id and content id are the same (I checked it in the pkg viewer program) and it should work but for some reason it doesn't... I'll send an image with the error it gives me

![error](https://user-images.githubusercontent.com/81699342/150432331-dcfed454-517b-452a-bcbb-9370f35a3d89.PNG)

Thank you! and I hope this has a solution :D

**Comment by enriquesomolinos** [comment]
can you share the info that shows pkg viewer?

**Comment by chronoss09** [comment]
same error, can't open any pkg :(
![Capture d’écran 2022-01-23 005442](https://user-images.githubusercontent.com/17669980/150659267-20364e85-da1d-4186-ac93-edf8b6cee222.png)

**Comment by enriquesomolinos** [comment]
can you download the new latest version (v.2.5.0) and post a screenshot of the error?

**Comment by chronoss09** [comment]
Samething for Far Cry 6
![FC6](https://user-images.githubusercontent.com/17669980/152149131-86708df3-3293-4e41-9018-cd0c5ff755db.PNG)

SpiderMan Miles Morales too
![MM](https://user-images.githubusercontent.com/17669980/152149167-e524728e-41c9-4b44-9179-c8f62fb20747.PNG)

**Comment by enriquesomolinos** [comment]
It seems that pkgripper does not understand the pkg file. This is due to your fake pkg tools, are probably outdated. Try to update it

**Comment by chronoss09** [comment]
I have the last version : Fake PKG Tools-3.87

**Comment by chronoss09** [comment]
For the first time, the program ask only 2 file to work : gengp4_app & orbis-pub-cmd
now, i put all pkg tool file on the same folder and it working...

![Capture d’écran 2022-02-03 021801](https://user-images.githubusercontent.com/17669980/152265161-ac84df69-05a4-4566-ab41-787737074474.png)

**Comment by chronoss09** [comment]
Fay Cry gime me only 203mo with 32Go on original file. It's correct ?
![Capture d’écran 2022-02-03 023557](https://user-images.githubusercontent.com/17669980/152266967-659d5582-823a-412f-aa57-c578cd847d2c.png)

**Comment by PhR34x0r** [comment]
Yes thats correct. Because they updated almost every file in the game, basically the whole game is in the update now so nearly all files from the base pkg can be deleted.
